### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by kenmazaika** [ramseychapin/firstProject#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ramseychapin** [comment]
Apologies for the delayed response. Just pushed and left a comment. Let me know what you think!

Ramsey Chapin
@ramseychapin ( https://twitter.com/ramseychapin )
about.me/ramseychapin ( http://about.me/ramseychapin )

**Comment by kenmazaika** [comment]
:+1:  Nice work on this!
